version: 2

jobs:
  unitTests:
    docker:
      - image: web3f/node:v0.1.0
    steps:
      - checkout
      - run: yarn
      - run:
          name: Run unit tests
          command: |
            yarn test

  e2eTests:
    docker:
      - image: web3f/node:v0.1.0
      - image: parity/polkadot:v0.8.16 
        name: polkadot
        command: --chain=kusama-dev --alice --ws-port 11000 --ws-external --rpc-methods=Unsafe --rpc-cors=all
    steps:
      - checkout
      - run: yarn
      - run:
          name: Run e2e tests
          command: |
            yarn e2e-test

  buildImage:
    docker:
      - image: web3f/ci-commons:v2.1.3
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            /scripts/build-image.sh web3f/accountant .

  helmLint:
    docker:
      - image: web3f/ci-commons:v2.1.3
    steps:
      - checkout
      - run:
          command: |
            helm lint ./charts/accountant

  integrationTests:
    docker:
      - image: web3f/ci-commons:v2.1.3
    steps:
      - checkout
      - setup_remote_docker
      - run:
          description: run integration tests
          command: |
            /scripts/integration-tests.sh

  publishImage:
    docker:
      - image: web3f/ci-commons:v2.1.3
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            /scripts/publish-image.sh web3f/accountant

  publishChart:
    docker:
      - image: web3f/ci-commons:v2.1.3
    steps:
      - checkout
      - run:
          command: |
            /scripts/publish-chart.sh

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - unitTests:
          filters:
            tags:
              only: /.*/
      - e2eTests:
          filters:
            tags:
              only: /.*/
      - helmLint:
          filters:
            tags:
              only: /.*/
      - buildImage:
          filters:
            tags:
              only: /.*/
          requires:
            - unitTests
            - e2eTests
      - integrationTests:
          filters:
            tags:
              only: /.*/
          requires:
            - buildImage
            - helmLint
      - publishImage:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          requires:
            - integrationTests
      - publishChart:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          requires:
            - integrationTests
